In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

C:\ProgramData\Anaconda3\lib\site-packages\scipy\__init__.py:138: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.23.1)
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion} is required for this version of "


# ========== Data ==========

In [2]:
data = pd.read_csv("dataset (2-class).csv")

In [3]:
data

x1        x2  y
0  -0.500938  0.180810  0
1  -0.616303 -0.018345  0
2  -0.665790 -0.185529  0
3   1.349299 -0.822487  1
4   1.557518  1.421756  1
..       ...       ... ..
95 -0.667931  0.328914  0
96 -0.578180 -0.632526  0
97  1.963141  0.334223  1
98 -0.273068 -2.842454  0
99 -1.463122  0.367013  0

[100 rows x 3 columns]

In [4]:
X_train_scaled = data[["x1", "x2"]]

In [5]:
y_train = data["y"]

# ========== Model ==========

## Setting Parameter

In [6]:
clf = LogisticRegression(penalty="none")

## Train Model

In [7]:
clf.fit(X_train_scaled, y_train)

LogisticRegression(penalty='none')

## Model's Weight & Bias

In [8]:
clf.intercept_

array([0.64193733])

In [9]:
clf.coef_

array([[4.48933489, 0.9014142 ]])

# ========== Prediction ==========

In [10]:
X_test_scaled = pd.read_csv("incoming_data (2-class).csv")

In [11]:
X_test_scaled

x1  x2
0   0   1
1   1   0
2  -1   0
3   0  -1

In [12]:
clf.predict(X_test_scaled)

array([1, 1, 0, 0], dtype=int64)

In [13]:
clf.predict_proba(X_test_scaled)

array([[0.17604859, 0.82395141],
       [0.00587433, 0.99412567],
       [0.97911049, 0.02088951],
       [0.56450769, 0.43549231]])